export const dealSlides = [
  {
    id: "01",
    title: "Spring Sale",
    discount: "30% OFF",
    image: "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=800",
  },
  {
    id: "02",
    title: "Summer Vibes",
    discount: "25% OFF",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800",
  },
  {
    id: "03",
    title: "New Arrival",
    discount: "40% OFF",
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800",
  },
];


export const navigation = [
  { name: "Home", href: "/" },
  { name: "Shop", href: "/shop" },
  { name: "Products", href: "/product" },
  {
    name: "Pages",
    href: "#Pages",
    submenu: [
      { name: "About Us", href: "#about" },
      { name: "Contact", href: "#contact" },
      { name: "FAQ", href: "#faq" },
    ],
  },
];

export  const navLinks =  ["/login","/registration","/ForgotPassword","/ConfirmationCode","/newpassword"]